### ISSUE TITLE
No sms synched on first install neither when received/sent

### ISSUE THREAD

**Issue by KLEINMIC** [nerzhul/ownCloud-SMS-App#23]
I installed the app on my server, in the appropriate directory, activated it in Owncloud, bought the Android app and created my owncloud-sms account.
It says it synchronizes, for a few seconds, but nothing appears in Owncloud.

Any solution ?

Thank you.

MK

**Comment by nerzhul** [comment]
If sync doesn't tell an error please look at owncloud.log in your data folder and apache logs.

**Comment by KLEINMIC** [comment]
Ok, according to the log file, I found the problem was coming from multiple adress book.
It is solved.

There is still a bunch of things to ameliorate : each time I close my Owncloud page, all SMS are uploaded again. 06.54.55... isnt the same as +336.54.55..., neither the same as 06 54 55... so the follow up is just impossible.
And finally, having a chance to send messages from the owncloud interface is quite the post important thing for me.

I don't think all this is a real big deal, but I really wish to have it working pretty soon.
Though, I am not sure your App was really ready for commercial SALE, right ?

Thank you for your work.

MK

**Comment by nerzhul** [comment]
Hi @KLEINMIC,
 the multiple address book issue is not a ocsms problem it's a contact app problem from owncloud, look at previous issues. You have dot in your phone numbers ? I can easily fix it into server side. Server 1.4 will add great features but multiple address book issue cannot be fixed, because the contact app exception is unhandlable into ocsms. Chat app has the same problem as mine.

**Comment by nerzhul** [comment]
https://github.com/nerzhul/ocsms/issues is the repo for server side, the deduplication is in the way. ocsms owncloud app v1.4 will fix the issue by selecting your country, and then convert your local phone numbers to intl phone numbers.
Sending from ocsms app is a little bit more difficult than sync, because i need to find the proper way to do it, a syncer is not the best thing to do it and there are many thing to handle into android app

**Comment by nerzhul** [comment]
ownCloud 8.0 and contact app may fix your issues. Is your problem solved ?

**Comment by nerzhul** [comment]
No news from user since 1 month
