### ISSUE TITLE
App crashes OS

### ISSUE THREAD

**Issue by brortao** [nerzhul/ownCloud-SMS-App#31]
Installing this app got my phone stuck in a boot logo loop - it would show the boot logo, then the lock screen for a few seconds, then repeat. Rebooting did not solve the issue.

I wish I could give more info but I had to restore my phone! The issue only started after setting up the app. I installed it from F-Droid.

I'm on Fairphone OS 1.8, based on Android 4.2.2. The Owncloud version is 8.0.0.

**Comment by nerzhul** [comment]
F-Droid is not the classic installation mode for this application, it's unofficial and unsupported by ownCloud-SMS-App team.
I also use ownCloud-SMS-App on Android 4.2.2 without issue on my production phone since the start of the development. I think you have a problem with your phone, not my app. App code is very basic and uses all the Android standard APIs

**Comment by brortao** [comment]
It seems likely that it has something to do with F-Droid. I factory reset my phone once, and re-installed ownCloud SMS (not realizing that it had caused the issue in the first place). The issue happened again, even on a "fresh" factory-reset phone.

Like I said, I wish I could give more info. I thought I'd submit a ticket anyway, just in case!

**Comment by nerzhul** [comment]
The only thing we must do is to branch your phone in debugging mode in an Eclipse with Android-SDK and look at the logcat logs to see what crash the phone.

**Comment by nerzhul** [comment]
own many messages would you sync ?

**Comment by brortao** [comment]
It was quite a lot of messages - over 1000 in total, I would say.

**Comment by nerzhul** [comment]
not many then.... without logs i could not find the issue :(

**Comment by brortao** [comment]
Unfortunately it's my everyday phone and I don't have time to risk resetting it again! If I do try to install the app again, I will update here.

**Comment by nerzhul** [comment]
Don't forget you use F-Droid, which is unofficial build, maybe this can add bugs

**Comment by CountMurphy** [comment]
If its any help, I've been running the client from fdroid as well. Zero issues.

**Comment by pejakm** [comment]
I'm having this issue, too. It started to happen when I changed sync interval to `never`. I solved the issue by manually removing this app via adb. I'm not sure how to debug this...

**Comment by nerzhul** [comment]
by changing to never ? this is very very strange, i'll look at this

**Comment by pejakm** [comment]
Yes, but it doesn't have to mean that exactly that triggered the bug. When restoring from boot loop, I deleted app's profile from /data/data first, but it didn't help until I removed app from /system/app (I had it installed as system app).

**Comment by nerzhul** [comment]
How many messages have you got @pejakm

**Comment by nerzhul** [comment]
@pejakm @brortao can you use logcat on your PC with you phone plugged in debug mode ?

**Comment by pejakm** [comment]
Sorry, I had to remove this app from my phone, because I can't afford another lockup. I'll try again some time, once I have a free weekend.

**Comment by nerzhul** [comment]
okay @pejakm , thanks

**Comment by pejakm** [comment]
I've tried just now, and same thing happens. Trigger appears to be setting sync interval to `never`. Will try to get some useful log from adb.

**Comment by pejakm** [comment]
Sorry, I have no usable output. I did notice that Mounts2SD couldn't mount dalvik-cache partition:
> E/Mounts2SD( 2749): It was not possible to attach '/sd-ext/dalvik-cache' to '/data/dalvik-cache' 
due to "low space on ext-sd partition" (altough that partition has plenty of space left). Once uninstalled ownCloud-SMS, everything went back to normal. I installed ownCloud-SMS again, set Sync frequency to "Never", and nothing happened (no crash). But the crash will probably happen again if I set up syncing account.

**Comment by nerzhul** [comment]
This week i diffuse accidentaly an instable fix on play store. 0.18.2 is correct

**Comment by pejakm** [comment]
I use version from F-Droid.

**Comment by nerzhul** [comment]
I don't know what version is on f-droid, if you could provide me

**Comment by pejakm** [comment]
https://f-droid.org/repository/browse/?fdfilter=ownCloud-SMS&fdid=fr.unix_experience.owncloud_sms
https://f-droid.org/wiki/page/fr.unix_experience.owncloud_sms

Ah, that might be it, I need to wait for update.

**Comment by nerzhul** [comment]
The current version is 0.18.2

**Comment by pejakm** [comment]
I have solved this by changing "pref_sync_frequency_values" value for `Never` from `-1` to `5256000` (ten years). Selecting this option doesn't cause OS crash anymore. So this ("Never" option) could be a problem. @brortao can you confirm?

@nerzhul Perhaps this option (`Never`) is not necessary: to my knowledge other sync services (DAVdroid, for example) don't provide it because one can easily turn off synchronization for a specific app via Android settings.

**Comment by nerzhul** [comment]
Okay, thanks for the tip. I doesn't have the issue on my phone and my emulators

**Comment by pejakm** [comment]
FWIW, I'm on Jelly Bean (4.2.2), rooted, stock rom. Only apps I run that I think could affect other apps on my phone to act strange are Xposed with GravityBox module and Mounts2SD. But never so far had I any problems with them.

**Comment by nerzhul** [comment]
@pejakm me too. I look at this issue since 1 week

**Comment by nerzhul** [comment]
Crash will be fixed with next release which be coming soon, this week if i get time to finish to solve some issues with translations :)
