### ISSUE TITLE
Do not sends SMS :(

### ISSUE THREAD

**Issue by kalinkin-43** [nerzhul/ownCloud-SMS-App#58]
1. How to send SMS from web-interface?
For example, https://mightytext.net/ allow to do it...

2. Not all my contacts are synchronised... a can see correct names only in ownclouds contacts :(

**Comment by nerzhul** [comment]
Hi @kalinkin-43 .
For the first point it's not possible atm, there are some security considerations and Android consideration to do it as a relay. It's a future feature, already in the list.

For the second point, please select a country in the web interface . ocsms doesn't sync contacts because we suppose you are using carddav contact, it's not the goal of this app :)

Thanks for your usage and suggestions

**Comment by kalinkin-43** [comment]
OK, hope future will come soon :) Untill that moment I'll continue to use  mightytext.net
